### ISSUE TITLE
â€‹ inserted at the start of (nearly) every track

### ISSUE THREAD

**Issue by Krigsmaskine** [crisbal/album-splitter#35]
Hi,

Love this bit of code and it has particularly helped me in sorting out music for game nights. There is a strange tendency, that I cannot nail down, that it very often inserts â€‹ into the start of the song title. It is even included in the dry run output;

![image](https://user-images.githubusercontent.com/39592771/115876589-ceda2180-a446-11eb-927a-e0835f43da2c.png)

[tracks.txt](https://github.com/crisbal/album-splitter/files/6365536/tracks.txt)

I do not know what exactly I am doing wrong, or why it only happens sometimes. Let me know if you need something else for troubleshooting.

**Comment by crisbal** [comment]
![Screenshot_2021-04-23-18-17-07-196_com android chrome](https://user-images.githubusercontent.com/2728038/115900366-289b1580-a460-11eb-85ac-394df5ba8d8e.jpg)

Hello, I also see the strange symbol in the tracks.txt file, see the attached screenshot, so it is definitely because of that. It is possible that your text editor does not show the symbol. Try to use an advanced text editor to clear the file up (I suggest Visual Studio Code) and make sure that the file encoding is set as UTF-8 (it is a setting you can specify even in standard notepad when you save the file)

**Comment by Krigsmaskine** [comment]
Ah shoot, I'm embarrassed, you are right. Thanks for checking it, dunno why I can't see it in my notepad programs (notepad++), but Wordpad shows it for some reason.

**Comment by IlyaMrz** [comment]
> Ah shoot, I'm embarrassed, you are right. Thanks for checking it, dunno why I can't see it in my notepad programs (notepad++), but Wordpad shows it for some reason.

you can open notepad++ > Encoding > Convert to ANSI .... -> Search >Replace > What to find: "?" and press "Replace all"
save and that's it
