### ISSUE TITLE
keeps giving me this error message and wont split the audio

### ISSUE THREAD

**Issue by lperez509** [crisbal/album-splitter#37]
Traceback (most recent call last):
  File "split.py", line 182, in <module>
    album = AudioSegment.from_file(FILENAME, 'wav')
  File "C:\Users\09515\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pydub\audio_segment.py", line 322, in from_file
    input_file.write(file.read())
MemoryError
i am on windows 10 wsl

**Comment by crisbal** [comment]
Hello, is it possible that the file to be split is very big and filling up your RAM? 

Unfortunately we had issues with very big files also here https://github.com/crisbal/album-splitter/issues/25

**Comment by lperez509** [comment]
is 4 hours very large?
it would download the full audio but would not split it

**Comment by lperez509** [comment]
i tested some other files and i believe it is the RAM that is the issue.
is there any other programs that you can recommend to run larger files?

**Comment by crisbal** [comment]
https://github.com/crisbal/album-splitter/issues/25#issuecomment-345504801 Here there are instructions to use another branch of the software that uses directly FFMPEG instead of a higher level library. It is possible that branch is very old and might now work still.

Otherwise you can look into alternative software such as Audacity in which you can manually split audio.

**Comment by lperez509** [comment]
tjaml you
