### ISSUE TITLE
Split from youtube leaves files in wav format

### ISSUE THREAD

**Issue by webworxshop** [crisbal/album-splitter#42]
Running `python -m album_splitter -yt <youtube_url>` appears to work correctly. However, the output files are all in wav format. The tool has been updated since the last time I used it, but this has always worked fine in the past.

Running on Arch Linux if that's of any relevance. Happy to provide further details as required.

**Comment by crisbal** [comment]
Hello! Yes, I have updated it a few weeks ago and made a change to output files in the same format as the input. Since YouTube downloads in wav, the output is wav.
I could add the option to specify the output format but it is probably better to do it afterwards with another tool (I think you can easily find some command to convert from wav to your desired format), since conversion could be tricky and riddled with options depending on the format.

Any reason why you don't like the wav?

**Comment by webworxshop** [comment]
Hi, thanks for getting back to me.

Sorry, I assumed it was a bug, since the behaviour has changed and no longer matches the documentation. I absolutely see the technical argument for leaving the files in the source format. For anyone finding this thread in future, I just transcoded the output files with Lame via the following command (executed from the output directory):

```
find . -iname "*.wav" -exec lame -V0 {} \;
```

Thanks for the awesome software!

**Comment by crisbal** [comment]
Thanks for the snippet

**Comment by kierun** [comment]
I was expecting `mp3` as well. I do not mind `album-splitter` stopping there and use the spinet from @webworxshop but an addition to the docs might be useful.
